id: A33D2D98E
title: Brief DharmapÄlas Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.485880
  last_modified_at: 2022-02-28 23:01:20.485884
