id: A33D2D98E
title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
  of India'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.482431
  last_modified_at: 2022-02-28 23:01:20.482439
