id: A33D2D98E
title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice of
  the Great Compassionate One, Natural Liberation of Suffering from The Heart Essence
  of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.500145
  last_modified_at: 2022-02-28 23:01:20.500148
