id: A33D2D98E
title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer to the
  Wisdom Ḍākinī Dechen Gyalmo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.501815
  last_modified_at: 2022-02-28 23:01:20.501818
