id: A33D2D98E
title: The Prayer to Guru Rinpoche for Attainments
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.498793
  last_modified_at: 2022-02-28 23:01:20.498796
