id: A33D2D98E
title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren) for
  the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the Great Compassionate
  One from the Longchen Nyingtik'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.497068
  last_modified_at: 2022-02-28 23:01:20.497071
