id: A33D2D98E
title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
  Deities of the Self-Liberated Wisdom Mind'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.488752
  last_modified_at: 2022-02-28 23:01:20.488755
