id: A33D2D98E
title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
  in Animals'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.503091
  last_modified_at: 2022-02-28 23:01:20.503094
