id: A33D2D98E
title: The Brief Ḍākinī Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:01:20.490812
  last_modified_at: 2022-02-28 23:01:20.490819
